branches:
  only:
    - develop
    - master

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - travis_retry composer install --no-interaction

env:
  matrix:
    - COMPOSER_ARGS=""
    - COMPOSER_ARGS="--prefer-lowest"

matrix:
  allow_failures:
    - php: 7.2
      env: COMPOSER_ARGS="--prefer-lowest"

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - phpunit --verbose

sudo: false

