branches:
  only:
    - develop
    - master

language: php

php:
  - 7.0

install:
  - travis_retry composer install --no-interaction

env:
  matrix:
    - COMPOSER_ARGS=""
    - COMPOSER_ARGS="--prefer-lowest"

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - phpunit --verbose

sudo: false

